-- Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  supplier TEXT,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_order TEXT NOT NULL,
  checkout_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  operator TEXT,
  status TEXT DEFAULT 'Completed',
  project TEXT
);

-- Create transaction_items table
CREATE TABLE IF NOT EXISTS transaction_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES inventory(id),
  product_name TEXT,
  quantity INTEGER,
  unit TEXT
);

-- Create checkout_transaction RPC function
CREATE OR REPLACE FUNCTION checkout_transaction(
  p_work_order TEXT,
  p_checkout_date TIMESTAMP WITH TIME ZONE,
  p_items JSONB
) RETURNS VOID AS $$
DECLARE
  v_transaction_id BIGINT;
  v_item JSONB;
  v_product_id BIGINT;
  v_quantity INTEGER;
BEGIN
  -- Insert transaction
  INSERT INTO transactions (work_order, checkout_date)
  VALUES (p_work_order, p_checkout_date)
  RETURNING id INTO v_transaction_id;

  -- Loop through items
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := (v_item->>'product_id')::BIGINT;
    v_quantity := (v_item->>'quantity')::INTEGER;

    -- Insert transaction item
    INSERT INTO transaction_items (transaction_id, product_id, product_name, quantity, unit)
    VALUES (
      v_transaction_id,
      v_product_id,
      v_item->>'product_name',
      v_quantity,
      v_item->>'unit'
    );

    -- Update inventory
    UPDATE inventory
    SET quantity = quantity - v_quantity,
        updated_at = NOW()
    WHERE id = v_product_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;
